<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KONTAKTI</name>
   <tag></tag>
   <elementGuidId>1d9ae6ec-27d6-4185-90a9-f11d11eadfd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='main-nav']/div/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2ac7b242-36fa-47cf-b4e5-525736a7ad5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/aplikacije/kontakti/</value>
      <webElementGuid>17ce4ca6-49e7-47ef-a457-5a69990f953f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KONTAKTI</value>
      <webElementGuid>dd09ed61-b0b8-4e7d-b8f7-58d12437ebcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-nav&quot;)/div[@class=&quot;block&quot;]/ul[1]/li[5]/a[1]</value>
      <webElementGuid>0d743261-e162-4d66-afca-c226611e63ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='main-nav']/div/ul/li[5]/a</value>
      <webElementGuid>1c52c347-6751-44bc-9b84-28933e246746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'KONTAKTI')])[2]</value>
      <webElementGuid>53584927-1722-4354-a4c9-732464d1a317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AKADEMIJA FERI'])[2]/following::a[1]</value>
      <webElementGuid>9c838fa6-77d8-46b1-ba52-4dff9d7887ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RAZISKOVANJE'])[2]/following::a[2]</value>
      <webElementGuid>df6cdbc4-3ce9-48eb-8391-9e867840b410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zapri primarno navigacijo'])[1]/preceding::a[1]</value>
      <webElementGuid>3f1e3311-1aee-4017-8430-a78bf8b63293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOVICE'])[1]/preceding::a[2]</value>
      <webElementGuid>6a61450a-5417-4e5e-9865-5693cef75935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/aplikacije/kontakti/')])[2]</value>
      <webElementGuid>a9aee943-a940-450d-a6c9-5984de9720f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/nav/div/ul/li[5]/a</value>
      <webElementGuid>eaef7a62-6114-47c6-985e-4878063812f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/aplikacije/kontakti/' and (text() = 'KONTAKTI' or . = 'KONTAKTI')]</value>
      <webElementGuid>f387f13f-f7a3-4e72-916f-b3cd8625de80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
